version: "3"
services:
  jenkins:
    user: 1000:999
    build: .
    ports:
      - 8080
    hostname: ${SERVICE}${ENVIRONMENT_SUFFIX}
    container_name: ${SERVICE}${ENVIRONMENT_SUFFIX}
    environment:
      DOMAIN: ${DOMAIN}
      ENVIRONMENT: ${ENVIRONMENT}
      SERVICE: ${SERVICE}
      HOST_IP: ${HOST_IP}
      SERVICE_8080_NAME: ${SERVICE}${ENVIRONMENT_SUFFIX}
      VIRTUAL_HOST: ${SERVICE}${ENVIRONMENT_SUFFIX}.${DOMAIN}
      VIRTUAL_PORT: 8080
      CASC_JENKINS_CONFIG: /var/jenkins_static/casc
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      SECRETS: /secrets
    extra_hosts:
      - "${SERVICE}.${DOMAIN}:${HOST_IP}"
      - "${SERVICE}test.${DOMAIN}:${HOST_IP}"
    volumes:
      - home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/vagrant/.ssh/jenkins:/secrets/ssh-agent-access-key
    networks:
      - prod
      - test
volumes:
  home:
    driver: local
networks:
  prod:
    external:
      name: prod
  test:
    external:
      name: test
