
node('master') {
    checkout scm
    def test = new File("${WORKSPACE}/docker/jenkins/env/test").readLines()
    withEnv(test + ["HOST_IP=${HOST_IP}","DOMAIN=${DOMAIN}"]) {
        dir("docker/jenkins"){
            stage('test build') {
              sh 'env'
              sh 'grep FROM Dockerfile | awk \'{print $2}\' | xargs docker pull'
              sh '''docker-compose -p ${SERVICE}${ENVIRONMENT} build && \
                    docker-compose -p ${SERVICE}${ENVIRONMENT} down -v && \
                    docker-compose -p ${SERVICE}${ENVIRONMENT} up -d'''
              sh 'echo sleeping to let jenkins boot up... && sleep 30'
              sh 'helpers/check_status_code https://${SERVICE}${ENVIRONMENT}.${DOMAIN}/login'
              sh 'docker-compose -p ${SERVICE}${ENVIRONMENT} down -v'
            }
        }
    }
}
node('vagrant') {
    def prod = new File("${WORKSPACE}/docker/jenkins/env/prod").readLines()
    withEnv(prod + ["HOST_IP=${HOST_IP}","DOMAIN=${DOMAIN}"]) {
        dir("docker/jenkins"){
            checkout scm
            stage('restart Jenkins') {
              sh '''docker-compose -p ${SERVICE}${ENVIRONMENT} build && \
                    docker-compose -p ${SERVICE}${ENVIRONMENT} down && \
                    docker-compose -p ${SERVICE}${ENVIRONMENT} up -d'''
            }
        }
    }
}
