node('master') {
    withEnv(['ENVIRONMENT=jenkinstest','DOMAIN=devbootstrap.dyindude']) {
        checkout scm
        stage('test build') {
          sh 'grep FROM Dockerfile | awk \'{print $2}\' | xargs docker pull'
          sh '''docker-compose -p ${ENVIRONMENT} build && \
                docker-compose -p ${ENVIRONMENT} down -v && \
                docker-compose -p ${ENVIRONMENT} up -d'''
          sh 'sleep 30'
          sh 'helpers/check_status_code https://${ENVIRONMENT}.${DOMAIN}/login'
          sh 'docker-compose -p ${ENVIRONMENT} down -v'
        }
    }
}
node('vagrant') {
    withEnv(['ENVIRONMENT=jenkins','DOMAIN=devbootstrap.dyindude']) {
        checkout scm
        stage('copy artifacts') {
          copyArtifacts('cidr')
        }
        stage('restart Jenkins') {
          sh '''docker-compose -p ${ENVIRONMENT} build && \
                docker-compose -p ${ENVIRONMENT} down && \
                docker-compose -p ${ENVIRONMENT} up -d'''
        }
    }
}
