---
- hosts: all
  vars:
    cert_directory: "certs" 
    cert_domain: "devbootstrap.dyindude"
  roles:
    - role: bootstrap
    - { role: cert, cert_hosts: [ "*" ], cert_canonical: true, cert_profile: "webapp" }
  tasks:
    - name: copy key to nginx folder
      copy:
        src: "/vagrant/certs/wildcard.{{ cert_domain }}-key.pem"
        dest: "/vagrant/docker/nginx/nginx-certs/{{ cert_domain }}.key"
        owner: vagrant
        group: vagrant
    - name: copy cert to nginx folder
      copy:
        src: "/vagrant/certs/wildcard.{{ cert_domain }}.pem"
        dest: "/vagrant/docker/nginx/nginx-certs/{{ cert_domain }}.crt"
        owner: vagrant
        group: vagrant
    - name: write HOST_IP to hostinfo
      shell: "echo HOST_IP={{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}} > /vagrant/docker/jenkins/hostinfo"
    - name: write DOMAIN to hostinfo
      shell: "echo DOMAIN={{ cert_domain }} >> /vagrant/docker/jenkins/hostinfo"
    - name: launch nginx
      shell: docker-compose up -d
      args:
        chdir: "{{ item }}"
      become: yes
      become_user: vagrant
      environment:
        HOST_IP: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
        DOMAIN: "{{ cert_domain }}"
        ENVIRONMENT: "jenkins"
      with_items:
        - "/vagrant/docker/nginx"
        - "/vagrant/docker/jenkins"
    - name: show public key to import to github
      debug:
        msg: "{{ lookup( 'file', '/home/vagrant/.ssh/jenkins.pub' ) }}"
