---
- hosts: all
  vars:
    cert_directory: "certs" 
    cert_domain: "devbootstrap.dyindude"
  roles:
    - role: bootstrap
    - { role: cert, cert_hosts: [ "*" ], cert_canonical: true, cert_profile: "webapp" }
  tasks:
    - name: copy key to nginx folder
      copy:
        src: "/vagrant/certs/wildcard.{{ cert_domain }}-key.pem"
        dest: "/vagrant/docker/nginx/nginx-certs/{{ cert_domain }}.key"
        owner: vagrant
        group: vagrant
    - name: copy cert to nginx folder
      copy:
        src: "/vagrant/certs/wildcard.{{ cert_domain }}.pem"
        dest: "/vagrant/docker/nginx/nginx-certs/{{ cert_domain }}.crt"
        owner: vagrant
        group: vagrant
    - name: make sure old hostinfo is missing
      file:
        path: /vagrant/hostinfo
        state: absent
    - name: write HOST_IP to hostinfo
      lineinfile:
        path: /vagrant/hostinfo
        line: "{{ item }}"
        state: present
        create: yes
      with_items:
        - "export HOST_IP={{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
        - "export DOMAIN={{ cert_domain }}"
